#!/usr/bin/env python3
"""Search toric fans for a relative MMP with a prescribed shape.

This is the tool that found the input of `tests/three-step-flip-mmp.m2` and
`examples/09-three-step-flip.m2`: a threefold over an affine base whose
minimal model program is exactly two divisorial contractions followed by a
flip.  Finding such a configuration by hand is not hard once, but the sizes
matter enormously -- the first hand-built candidate needed fourteen minutes and
5.4 GB just to decide its canonical index, where the one this search returned
needs 0.9 seconds -- and the size only becomes visible after the fan and the
polarization are both fixed.  So the search is over both.

The whole MMP with scaling is simulated combinatorially, with no algebra:

  * Every wall (a 2-dimensional cone shared by two maximal cones) of a
    simplicial fan carries a relation `sum a_i v_i = 0`, unique up to scale and
    normalized so that the two rays outside the wall have positive
    coefficients.  For a divisor `D = sum c_i D_i` the intersection number with
    the wall curve is `D.C = sum a_i c_i`, so `K.C = -sum a_i`.
  * The Mori cone relative to the base is generated by the wall curve classes
    (Reid), so the nef threshold of `K + tH` is `max -K.C/H.C` over the walls,
    and the face contracted at that threshold is spanned by the walls attaining
    it.
  * The type of the contraction is read off the *negative* support of the
    relation: no negative entries is a fibration, exactly one is a divisorial
    contraction of that ray's divisor, two or more is a flip.
  * A divisorial step deletes the ray, and the polarization the next step
    carries is `K + t*H` restricted to the remaining rays -- which is what
    `threefoldMMPData` hands to its own next iteration.  Rather than implement
    the general merge of the cones around a deleted ray, the search builds the
    fans upward by star subdivision and checks that the program walks back down
    the same way.

Usage:  python3 toric-relative-mmp-search.py
Prints every (w, w2, H) whose program over the circuit base of example 7 is
{divisorial contracting w2, divisorial contracting w, flip}, sorted by the size
of the polarization.  Feed the survivors to Macaulay2 to score them by the
number of generators of the section ring, which is what the cost tracks.
"""
from fractions import Fraction as F
from itertools import combinations
import math

# --- the fan and its walls ---------------------------------------------------


def det3(a, b, c):
    return (a[0] * (b[1] * c[2] - b[2] * c[1]) - a[1] * (b[0] * c[2] - b[2] * c[0])
            + a[2] * (b[0] * c[1] - b[1] * c[0]))


def solve3(cols, rhs):
    """Solve (cols as columns) x = rhs over Q, or None if singular."""
    M = [[F(cols[j][i]) for j in range(3)] + [F(rhs[i])] for i in range(3)]
    for i in range(3):
        p = next((r for r in range(i, 3) if M[r][i] != 0), None)
        if p is None:
            return None
        M[i], M[p] = M[p], M[i]
        piv = M[i][i]
        M[i] = [v / piv for v in M[i]]
        for r in range(3):
            if r != i and M[r][i] != 0:
                f = M[r][i]
                M[r] = [M[r][k] - f * M[i][k] for k in range(4)]
    return [M[i][3] for i in range(3)]


def wall_classes(rays, cones):
    """[(relation vector over all rays, the wall)] for every wall of the fan."""
    out = []
    for i, j in combinations(range(len(cones)), 2):
        tau = sorted(set(cones[i]) & set(cones[j]))
        if len(tau) != 2:
            continue
        k = [x for x in cones[i] if x not in tau][0]
        l = [x for x in cones[j] if x not in tau][0]
        x = solve3([rays[l], rays[tau[0]], rays[tau[1]]], [-c for c in rays[k]])
        if x is None:
            continue
        rel = {k: F(1), l: x[0], tau[0]: x[1], tau[1]: x[2]}
        if x[0] <= 0:
            x2 = solve3([rays[k], rays[tau[0]], rays[tau[1]]],
                        [-c for c in rays[l]])
            if x2 is None or x2[0] <= 0:
                continue
            rel = {l: F(1), k: x2[0], tau[0]: x2[1], tau[1]: x2[2]}
        den = 1
        for v in rel.values():
            den = den * v.denominator // math.gcd(den, v.denominator)
        out.append((tuple(rel.get(t, F(0)) * den for t in range(len(rays))),
                    tuple(tau)))
    return out


def star_subdivision(rays, cones, p):
    """Insert the ray p, or None if p lies in no cone of the fan."""
    if p in rays:
        return None
    index, newcones, touched = len(rays), [], 0
    for c in cones:
        lam = solve3([rays[i] for i in c], p)
        if lam is None:
            return None
        if all(v >= 0 for v in lam):
            touched += 1
            for i in range(3):
                if lam[i] > 0:
                    newcones.append(
                        sorted([c[j] for j in range(3) if j != i] + [index]))
        else:
            newcones.append(sorted(c))
    return (rays + [p], newcones) if touched else None


def step(classes, kco, hco, n):
    """One step of the MMP with scaling: (kind, threshold, data)."""
    best, attaining = None, []
    for vec, _ in classes:
        hd = sum(vec[i] * hco[i] for i in range(n))
        if hd <= 0:
            return None                                   # H is not ample
        kd = sum(vec[i] * kco[i] for i in range(n))
        t = F(-kd, 1) / hd
        if best is None or t > best:
            best, attaining = t, [vec]
        elif t == best:
            attaining.append(vec)
    if best is None or best <= 0:
        return ("nef", best, None)
    negative = set()
    for vec in attaining:
        negative |= {i for i in range(n) if vec[i] < 0}
    if len(negative) == 0:
        return ("fibre", best, None)
    if len(negative) == 1:
        return ("divisorial", best, negative.pop())
    return ("flip", best, sorted(negative))


# --- the search --------------------------------------------------------------


def primitive(p):
    return math.gcd(math.gcd(abs(p[0]), abs(p[1])), abs(p[2])) == 1


def main():
    # Example 7's base: the circuit v1 + v2 = 2 v3 + v4, whose flipping
    # triangulation Y has one 1/2(1,1,1) point.
    v1, v2, v3, v4 = (1, 0, 0), (0, 1, 0), (0, 0, 1), (1, 1, -2)
    raysY, conesY = [v1, v2, v3, v4], [[0, 1, 2], [0, 1, 3]]
    classesY = wall_classes(raysY, conesY)

    box = [(a, b, c) for a in range(0, 3) for b in range(0, 3)
           for c in range(-3, 1) if (a, b, c) != (0, 0, 0) and primitive((a, b, c))]
    # The coefficients of H are only defined modulo the principal divisors
    # div(x^m) = (<m,v_i>)_i, a rank-three lattice, and v1, v2, v3 are a basis of
    # N; so setting the first three coefficients to zero uses that freedom up
    # exactly, and the remaining three range over the relative Picard rank.
    found = []
    for w in box:
        first = star_subdivision(raysY, conesY, w)
        if first is None:
            continue
        rays1, cones1 = first
        classes1 = wall_classes(rays1, cones1)
        for w2 in box:
            second = star_subdivision(rays1, cones1, w2)
            if second is None:
                continue
            rays2, cones2 = second
            classes2 = wall_classes(rays2, cones2)
            mults = [abs(det3(*[rays2[i] for i in c])) for c in cones2]
            for c4 in range(-5, 6):
                for cw in range(-5, 6):
                    for cw2 in range(-5, 6):
                        h = [F(0), F(0), F(0), F(c4), F(cw), F(cw2)]
                        r = step(classes2, [F(-1)] * 6, h, 6)
                        if r is None or r[0] != "divisorial" or r[2] != 5:
                            continue
                        L = [F(-1) + r[1] * h[i] for i in range(5)]
                        r1 = step(classes1, [F(-1)] * 5, L, 5)
                        if r1 is None or r1[0] != "divisorial" or r1[2] != 4:
                            continue
                        Lp = [F(-1) + r1[1] * L[i] for i in range(4)]
                        r2 = step(classesY, [F(-1)] * 4, Lp, 4)
                        if r2 is None or r2[0] != "flip":
                            continue
                        found.append({
                            "w": w, "w2": w2, "H": [0, 0, 0, c4, cw, cw2],
                            "thresholds": [str(r[1]), str(r1[1]), str(r2[1])],
                            "L": [str(x) for x in L],
                            "Lprime": [str(x) for x in Lp],
                            "sourceIsSmooth": max(mults) == 1})
    print("configurations giving {divisorial, divisorial, flip}: %d" % len(found))
    found.sort(key=lambda d: (not d["sourceIsSmooth"],
                              sum(abs(x) for x in d["H"])))
    for d in found[:20]:
        print("  w=%s w2=%s H=%s t=%s L=%s L'=%s%s" % (
            d["w"], d["w2"], d["H"], d["thresholds"], d["L"], d["Lprime"],
            "  (smooth source)" if d["sourceIsSmooth"] else ""))
    # The one that was used: w=(1,1,-1) resolves the 1/2(1,1,1) point and
    # w2=(1,2,-2)=v2+v4 sits on a facet of sigma, with H = 4D_v4 + D_w + 3D_w2.
    # Its section rings have 11, 9, 7 and 7 generators and its source is smooth,
    # so the canonical index is 1 -- on two otherwise equal 11-generator sources,
    # index 1 against index 2 was 12 s against 424 s for the fibre-curve degrees.


if __name__ == "__main__":
    main()
